# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scientific Services Limited
email: tim@fortmarketing.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Scientific Services new website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# COLLECTIONS
collections_dir: collections
collections:
  alert:
    output: false
  all_purpose:
    output: true
  case_studies:
    output: true
  company:
    output: true
  knowledge_base:
    output: true
  marketing_banners:
    output: false
  services:
    output: true
  testimonials:
    output: false
  videos:
    output: false

# DEFAULTS
defaults:
  -
    scope:
      path: "_services/asbestos/primary"
    values:
        layout: "primary"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "asbestos"
        news_archive: "/services/asbestos/news/archive/"
        case_studies: "/services/asbestos/case-studies/"
  -
    scope:
      path: "_services/legionella/primary"
    values:
        layout: "primary"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "legionella"
        news_archive: "/services/legionella/news/archive/"
        case_studies: "/services/legionella/case-studies/"
  -
    scope:
      path: "_services/anthrax/primary"
    values:
        layout: "primary"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "anthrax"
        news_archive: "/services/anthrax/news/archive/"
        case_studies: "/services/anthrax/case-studies/"
  -
    scope:
      path: "_services/lead-testing/primary"
    values:
        layout: "primary"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "lead-testing"
        news_archive: "/services/lead-testing/news/archive/"
        case_studies: "/services/lead-testing/case-studies/"
  -
    scope:
      path: "_services/expert-witness/primary"
    values:
        layout: "primary"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "expert-witness"
        news_archive: "/services/expert-witness/news/archive/"
        case_studies: "/services/expert-witness/case-studies/"
  -
    scope:
      path: "_services/laboratory-auditing/primary"
    values:
        layout: "primary"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "laboratory-auditing"
        news_archive: "/services/laboratory-auditing/news/archive/"
        case_studies: "/services/laboratory-auditing/case-studies/"
  -
    scope:
      path: "_services/asbestos/secondary"
    values:
        layout: "secondary"
        permalink: "/services/asbestos/:name/"
        landing_page_type: "secondary"
        parent_category: "asbestos"
  -
    scope:
      path: "_services/legionella/secondary"
    values:
        layout: "secondary"
        permalink: "/services/legionella/:name/"
        landing_page_type: "secondary"
        parent_category: "legionella"
  -
    scope:
      path: "_services/anthrax/secondary"
    values:
        layout: "secondary"
        permalink: "/services/anthrax/:name/"
        landing_page_type: "secondary"
        parent_category: "anthrax"
  -
    scope:
      path: "_services/lead-testing/secondary"
    values:
        layout: "secondary"
        permalink: "/services/lead-testing/:name/"
        landing_page_type: "secondary"
        parent_category: "lead-testing"
  -
    scope:
      path: "_services/expert-witness/secondary"
    values:
        layout: "secondary"
        permalink: "/services/expert-witness/:name/"
        landing_page_type: "secondary"
        parent_category: "expert-witness"
  -
    scope:
      path: "_services/laboratory-auditing/secondary"
    values:
        layout: "secondary"
        permalink: "/services/laboratory-auditing/:name/"
        landing_page_type: "secondary"
        parent_category: "laboratory-auditing"
  -
    scope:
      path: "_case_studies/anthrax"
    values:
        layout: "default"
        permalink: "/services/anthrax/case-studies/:name/"
        parent_category: "anthrax"
  -
    scope:
      path: "_case_studies/asbestos"
    values:
        layout: "default"
        permalink: "/services/asbestos/case-studies/:name/"
        parent_category: "asbestos"
  -
    scope:
      path: "_case_studies/expert-witness"
    values:
        layout: "default"
        permalink: "/services/expert-witness/case-studies/:name/"
        parent_category: "expert-witness"
  -
    scope:
      path: "_case_studies/laboratory-auditing"
    values:
        layout: "default"
        permalink: "/services/laboratory-auditing/case-studies/:name/"
        parent_category: "laboratory-auditing"
  -
    scope:
      path: "_case_studies/lead-testing"
    values:
        layout: "default"
        permalink: "/services/lead-testing/case-studies/:name/"
        parent_category: "lead-testing"
  -
    scope:
      path: "_case_studies/legionella"
    values:
        layout: "default"
        permalink: "/services/legionella/case-studies/:name/"
        parent_category: "legionella"
  -
    scope:
      path: "_posts/anthrax"
    values:
        layout: "default"
        permalink: "/services/anthrax/news/:name/"
        parent_category: "anthrax"
  -
    scope:
      path: "_posts/asbestos"
    values:
        layout: "default"
        permalink: "/services/asbestos/news/:name/"
        parent_category: "asbestos"
  -
    scope:
      path: "_posts/company"
    values:
        layout: "default"
        permalink: "/services/about/news/:name/"
        parent_category: "company"
  -
    scope:
      path: "_posts/expert-witness"
    values:
        layout: "default"
        permalink: "/services/expert-witness/news/:name/"
        parent_category: "expert-witness"
  -
    scope:
      path: "_posts/laboratory-auditing"
    values:
        layout: "default"
        permalink: "/services/laboratory-auditing/news/:name/"
        parent_category: "laboratory-auditing"
  -
    scope:
      path: "_posts/lead-testing"
    values:
        layout: "default"
        permalink: "/services/lead-testing/news/:name/"
        parent_category: "lead-testing"
  -
    scope:
      path: "_posts/legionella"
    values:
        layout: "default"
        permalink: "/services/legionella/news/:name/"
        parent_category: "legionella"
  -
    scope:
      path: "_knowledge_base/anthrax"
    values:
        layout: "default"
        permalink: "/services/anthrax/:name/"
        parent_category: "anthrax"
        child_category: "anthrax"
  -
    scope:
      path: "_knowledge_base/asbestos/surveys"
    values:
        layout: "default"
        permalink: "/services/asbestos/surveys/:name/"
        parent_category: "asbestos"
        child_category: "surveys"
  -
    scope:
      path: "_knowledge_base/asbestos/testing"
    values:
        layout: "default"
        permalink: "/services/asbestos/testing/:name/"
        parent_category: "asbestos"
        child_category: "testing"
  -
    scope:
      path: "_knowledge_base/asbestos/removal"
    values:
        layout: "default"
        permalink: "/services/asbestos/removal/:name/"
        parent_category: "asbestos"
        child_category: "removal"
  -
    scope:
      path: "_knowledge_base/asbestos/air-monitoring"
    values:
        layout: "default"
        permalink: "/services/asbestos/air-monitoring/:name/"
        parent_category: "asbestos"
        child_category: "air-monitoring"
  -
    scope:
      path: "_knowledge_base/asbestos/awareness-training"
    values:
        layout: "default"
        permalink: "/services/asbestos/awareness-training/:name/"
        parent_category: "asbestos"
        child_category: "awareness-training"
  -
    scope:
      path: "_knowledge_base/legionella/risk-assessment"
    values:
        layout: "default"
        permalink: "/services/legionella/risk-assessment/:name/"
        parent_category: "legionella"
        child_category: "risk-assessment"
  -
    scope:
      path: "_knowledge_base/legionella/monitoring"
    values:
        layout: "default"
        permalink: "/services/legionella/monitoring/:name/"
        parent_category: "legionella"
        child_category: "monitoring"
  -
    scope:
      path: "_knowledge_base/legionella/removal"
    values:
        layout: "default"
        permalink: "/services/legionella/removal/:name/"
        parent_category: "legionella"
        child_category: "removal"
  -
    scope:
      path: "_knowledge_base/lead-testing"
    values:
        layout: "default"
        permalink: /services/lead-testing/:name/
        parent_category: "lead-testing"
        child_category: "lead-testing"





# FILE UPLOADS
uploads_dir: /images/uploads



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
