# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Scientific Services Limited
email: tim@fortmarketing.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Scientific Services new website.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# COLLECTIONS
collections_dir: collections
collections:
  alert:
    output: false
  all_purpose:
    output: true
  company:
    output: true
  knowledge_base:
    output: true
  services:
    output: true

# DEFAULTS
defaults:
  -
    scope:
      path: "_services/asbestos/primary"
    values:
        layout: "default"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "asbestos"
  -
    scope:
      path: "_services/legionella/primary"
    values:
        layout: "default"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "legionella"
  -
    scope:
      path: "_services/anthrax/primary"
    values:
        layout: "default"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "anthrax"
  -
    scope:
      path: "_services/lead-testing/primary"
    values:
        layout: "default"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "lead-testing"
  -
    scope:
      path: "_services/expert-witness/primary"
    values:
        layout: "default"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "expert-witness"
  -
    scope:
      path: "_services/laboratory-auditing/primary"
    values:
        layout: "default"
        permalink: "/services/:name/"
        landing_page_type: "primary"
        child_page_type: "secondary"
        child_page_category: "laboratory-auditing"
  -
    scope:
      path: "_services/asbestos/secondary"
    values:
        layout: "default"
        permalink: "/services/asbestos/:name/"
        landing_page_type: "secondary"
  -
    scope:
      path: "_services/legionella/secondary"
    values:
        layout: "default"
        permalink: "/services/legionella/:name/"
        landing_page_type: "secondary"
  -
    scope:
      path: "_services/anthrax/secondary"
    values:
        layout: "default"
        permalink: "/services/anthrax/:name/"
        landing_page_type: "secondary"
  -
    scope:
      path: "_services/lead-testing/secondary"
    values:
        layout: "default"
        permalink: "/services/lead-testing/:name/"
        landing_page_type: "secondary"
  -
    scope:
      path: "_services/expert-witness/secondary"
    values:
        layout: "default"
        permalink: "/services/expert-witness/:name/"
        landing_page_type: "secondary"
  -
    scope:
      path: "_services/laboratory-auditing/secondary"
    values:
        layout: "default"
        permalink: "/services/laboratory-auditing/:name/"
        landing_page_type: "secondary"




# FILE UPLOADS
uploads_dir: /images/uploads



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
